### ISSUE TITLE
java.lang.NoClassDefFoundError when running

### ISSUE THREAD

**Issue by 0x6D70** [opencrx/opencrx-custom#7]
I am using the latest version. It compiles and start successfully.
I start it with Tomcat without problems.
When I then navigate to ``http://localhost:8080/opencrx-store-CRX/Store.jsp`` I get a ``java.lang.NoClassDefFoundError`` exception.
This is my log file:
```
März 11, 2021 10:09:38 NACHM. org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [/opencrx-store-CRX] threw exception [javax.servlet.ServletException: java.lang.NoClassDefFoundError: javax/resource/ResourceException] with root cause
java.lang.NoClassDefFoundError: javax/resource/ResourceException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructors(Class.java:1943)
	at org.openmdx.kernel.loading.Classes.newApplicationInstance(Classes.java:450)
	at org.openmdx.kernel.loading.Classes.newPlatformInstance(Classes.java:550)
	at org.openmdx.base.mof.spi.Model_1Factory.loadModel(Model_1Factory.java:284)
	at org.openmdx.base.mof.spi.Model_1Factory.loadModel(Model_1Factory.java:155)
	at org.openmdx.base.mof.spi.Model_1Factory.getModel(Model_1Factory.java:129)
	at org.openmdx.base.mof.spi.Model_1Factory.getModel(Model_1Factory.java:108)
	at org.opencrx.kernel.utils.Utils.getModel(Utils.java:150)
	at org.opencrx.sample.store.common.util.ApplicationContextFactory.createContext(ApplicationContextFactory.java:74)
	at org.apache.jsp.Store_jsp._jspService(Store_jsp.java:109)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2531)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2520)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by wfro64** [comment]
The Store app requires a Java EE Web Profile compliant application server, e.g. TomEE webprofile (http://tomee.apache.org/download-ng.html). Moreover it requires a running and configured openCRX Server as backend. Documentation updated accordingly https://github.com/opencrx/opencrx-documentation/blob/master/Sdk/CustomProject.md
